# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationrequest',
            name='merchant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='confirmationrequest',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
