# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170505_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationrequest',
            name='contribution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Contribution'),
        ),
    ]
